[2022-06-22 10:34:17,819] {processor.py:163} INFO - Started process (PID=25039) to work on /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:34:17,820] {processor.py:642} INFO - Processing file /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py for tasks to queue
[2022-06-22 10:34:17,820] {logging_mixin.py:109} INFO - [2022-06-22 10:34:17,820] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:34:18,297] {logging_mixin.py:109} INFO - [2022-06-22 10:34:18,296] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py", line 195, in <module>
    on_success_callback=task_success_log
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/plugins/Postgres2SMB_decrypt.py", line 28, in __init__
    super(Postgres2SMB_decrypt, self).__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 537, in __init__
    "arguments were:\n**kwargs: {k}".format(c=self.__class__.__name__, k=kwargs, t=task_id),
airflow.exceptions.AirflowException: Invalid arguments were passed to Postgres2SMB_decrypt (task_id: transfer_cos_smb). Invalid arguments were:
**kwargs: {'decr_col': ['MOFID', 'TXT_LONG']}
[2022-06-22 10:34:18,303] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:34:18,309] {processor.py:171} INFO - Processing /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py took 0.492 seconds
[2022-06-22 10:34:49,017] {processor.py:163} INFO - Started process (PID=25183) to work on /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:34:49,018] {processor.py:642} INFO - Processing file /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py for tasks to queue
[2022-06-22 10:34:49,018] {logging_mixin.py:109} INFO - [2022-06-22 10:34:49,018] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:34:49,414] {logging_mixin.py:109} INFO - [2022-06-22 10:34:49,413] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py", line 195, in <module>
    on_success_callback=task_success_log
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/plugins/Postgres2SMB_decrypt.py", line 28, in __init__
    super(Postgres2SMB_decrypt, self).__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 537, in __init__
    "arguments were:\n**kwargs: {k}".format(c=self.__class__.__name__, k=kwargs, t=task_id),
airflow.exceptions.AirflowException: Invalid arguments were passed to Postgres2SMB_decrypt (task_id: transfer_cos_smb). Invalid arguments were:
**kwargs: {'decr_col': ['MOFID', 'TXT_LONG']}
[2022-06-22 10:34:49,417] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:34:49,445] {processor.py:171} INFO - Processing /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py took 0.430 seconds
[2022-06-22 10:35:19,935] {processor.py:163} INFO - Started process (PID=25338) to work on /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:35:19,940] {processor.py:642} INFO - Processing file /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py for tasks to queue
[2022-06-22 10:35:19,942] {logging_mixin.py:109} INFO - [2022-06-22 10:35:19,941] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:35:20,433] {logging_mixin.py:109} INFO - [2022-06-22 10:35:20,433] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py", line 195, in <module>
    on_success_callback=task_success_log
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/plugins/Postgres2SMB_decrypt.py", line 28, in __init__
    super(Postgres2SMB_decrypt, self).__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 537, in __init__
    "arguments were:\n**kwargs: {k}".format(c=self.__class__.__name__, k=kwargs, t=task_id),
airflow.exceptions.AirflowException: Invalid arguments were passed to Postgres2SMB_decrypt (task_id: transfer_cos_smb). Invalid arguments were:
**kwargs: {'decr_col': ['MOFID', 'TXT_LONG']}
[2022-06-22 10:35:20,436] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:35:20,441] {processor.py:171} INFO - Processing /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py took 0.510 seconds
[2022-06-22 10:35:50,962] {processor.py:163} INFO - Started process (PID=25488) to work on /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:35:50,963] {processor.py:642} INFO - Processing file /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py for tasks to queue
[2022-06-22 10:35:50,963] {logging_mixin.py:109} INFO - [2022-06-22 10:35:50,963] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:35:51,367] {logging_mixin.py:109} INFO - [2022-06-22 10:35:51,366] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py", line 195, in <module>
    on_success_callback=task_success_log
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/decorators.py", line 50, in wrapper
    return func(*args, **kwargs)
  File "/opt/airflow/plugins/Postgres2SMB_decrypt.py", line 28, in __init__
    super(Postgres2SMB_decrypt, self).__init__(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 188, in apply_defaults
    result = func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 537, in __init__
    "arguments were:\n**kwargs: {k}".format(c=self.__class__.__name__, k=kwargs, t=task_id),
airflow.exceptions.AirflowException: Invalid arguments were passed to Postgres2SMB_decrypt (task_id: transfer_cos_smb). Invalid arguments were:
**kwargs: {'decr_col': ['MOFID', 'TXT_LONG']}
[2022-06-22 10:35:51,370] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py
[2022-06-22 10:35:51,375] {processor.py:171} INFO - Processing /opt/airflow/dags/cos_6611/cos_6611_ipo_2_cos_calendar.py took 0.415 seconds
